### ISSUE TITLE
[error]Can not convert Object to String

### ISSUE THREAD

**Issue by crp746rb** [SQLPlayer/azure.datafactory.tools#177]
**Describe the bug**
Using your Devops Publish ADF task getting this error.

When the devops release task to publish the json files reaches the "STEP: Deleting objects not in source ..." we then get the above message.

2022-01-11T20:37:23.2499867Z Finished deploying object: [factory].[PRUSA-DW-ADF-DEV]
2022-01-11T20:37:23.2505406Z ===================================================================================
2022-01-11T20:37:23.2510520Z STEP: Deleting objects not in source ...
2022-01-11T20:37:23.7948787Z Azure Data Factory (instance) loaded.
2022-01-11T20:37:26.3276144Z ##[error]Can not convert Object to String.
2022-01-11T20:37:26.4442729Z ##[section]Finishing: Publish ADF PRUSA-DW-ADF-QA from JSON files

I am not sure what version of your tool I have.  There are no errors in the ADF branch that I am deploying from.  This task worked the last I looked at it but no one noticed when this error started and it has been longer than 30 days so all past successfully jobs logs are gone.

I'm setup this release task early last year.  I am trying to confirm what version I have to what you have available.

The job is failing when it goes to delete the objects in the target that no longer exist.  I have done those deletes myself in the target.  The deployment still failed thou on this step.

**Comment by crp746rb** [comment]
Confirmed I have the latest version of the extension.

**Comment by crp746rb** [comment]
I haven't figure out what is causing this error message.  I am hoping you have a way of adding some more details to that error message.

**Comment by NowinskiK** [comment]
This must be caused by one of the objects in your ADF. The provided log is not showing that details.
Probably it's related to bug in Microsoft Az.DataFactory module, which is used to get objects from the ADF instance.
Try to identify the object reading the log and then run `Get-AzDataFactoryV2***` cmdlet for that object.
It may be similar to this issue: https://github.com/SQLPlayer/azure.datafactory.tools/issues/85

**Comment by crp746rb** [comment]
How do I get the #debug lines in the log like I see show in the log in issue 85?  My log isn't helping me out with what object to look at.

**Comment by NowinskiK** [comment]
Set `System.Debug` variable = `true` in Azure DevOps Pipeline:
![image](https://user-images.githubusercontent.com/25029325/149632244-90809929-47dc-4b43-af2c-5b7d8e029cf8.png)
or (if you use PowerShell session) set the mode like this:
`$DebugPreference = 'Continue'`

**Comment by crp746rb** [comment]
Thanks.  Have a debug log.  Still not very helpful to narrow down which object.  One of my datasets I think.  I am guessing next thing to try would be the powershell command to see if I can narrow down which one it is.  I don't even know what update was made when this started, the other developers didn't even notice this error and I don't have a log of the last successful deployment.  Here is what I have in the debug log

2022-01-17T16:00:41.9334470Z ===================================================================================
2022-01-17T16:00:41.9341355Z STEP: Deleting objects not in source ...
2022-01-17T16:00:43.0883200Z Azure Data Factory (instance) loaded.
2022-01-17T16:00:46.2354961Z ##[debug]Leaving D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.11.1070\PublishADF.ps1.
2022-01-17T16:00:46.2708018Z ##[debug]Caught exception from task script.
2022-01-17T16:00:46.2736490Z ##[debug]Error record:
2022-01-17T16:00:46.3452901Z ##[debug]Get-AzDataFactoryV2Dataset : Can not convert Object to String.
2022-01-17T16:00:46.3454774Z ##[debug]At D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.11.1070\ps_modules\azure.datafactory.tools\public\Get-AdfFromService.ps1:40 char:21
2022-01-17T16:00:46.3466940Z ##[debug]+ ... .DataSets = Get-AzDataFactoryV2Dataset -ResourceGroupName "$ResourceG ...
2022-01-17T16:00:46.3478958Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-01-17T16:00:46.3490878Z ##[debug]    + CategoryInfo          : CloseError: (:) [Get-AzDataFactoryV2Dataset], ArgumentException
2022-01-17T16:00:46.3502840Z ##[debug]    + FullyQualifiedErrorId : Microsoft.Azure.Commands.DataFactoryV2.GetAzureDataFactoryDatasetCommand
2022-01-17T16:00:46.3521821Z ##[debug] 
2022-01-17T16:00:46.3558025Z ##[debug]Script stack trace:
2022-01-17T16:00:46.3570367Z ##[debug]at Get-AdfFromService, D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.11.1070\ps_modules\azure.datafactory.tools\public\Get-AdfFromService.ps1: line 40
2022-01-17T16:00:46.3582968Z ##[debug]at Publish-AdfV2FromJson, D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.11.1070\ps_modules\azure.datafactory.tools\public\Publish-AdfV2FromJson.ps1: line 221
2022-01-17T16:00:46.3594938Z ##[debug]at <ScriptBlock>, D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.11.1070\PublishADF.ps1: line 128
2022-01-17T16:00:46.3607460Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-01-17T16:00:46.3619243Z ##[debug]at <ScriptBlock>, <No file>: line 22
2022-01-17T16:00:46.3631053Z ##[debug]at <ScriptBlock>, <No file>: line 18
2022-01-17T16:00:46.3699811Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-01-17T16:00:46.3718285Z ##[debug]Exception:
2022-01-17T16:00:46.3796241Z ##[debug]System.ArgumentException: Can not convert Object to String.
2022-01-17T16:00:46.3808424Z ##[debug]   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
2022-01-17T16:00:46.3868433Z ##[debug]   at Microsoft.Rest.Serialization.PolymorphicDeserializeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
2022-01-17T16:00:46.3873289Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
2022-01-17T16:00:46.3885080Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2022-01-17T16:00:46.3886492Z ##[debug]   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
2022-01-17T16:00:46.3887946Z ##[debug]   at Microsoft.Rest.Serialization.PolymorphicDeserializeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
2022-01-17T16:00:46.3889409Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
2022-01-17T16:00:46.3891034Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
2022-01-17T16:00:46.3902961Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2022-01-17T16:00:46.3915388Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2022-01-17T16:00:46.3928009Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
2022-01-17T16:00:46.3940190Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
2022-01-17T16:00:46.3953515Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
2022-01-17T16:00:46.3965876Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2022-01-17T16:00:46.3978268Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2022-01-17T16:00:46.3990424Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2022-01-17T16:00:46.3998438Z ##[debug]   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
2022-01-17T16:00:46.4012704Z ##[debug]   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
2022-01-17T16:00:46.4024656Z ##[debug]   at Microsoft.Azure.Management.DataFactory.DatasetsOperations.<ListByFactoryNextWithHttpMessagesAsync>d__9.MoveNext()
2022-01-17T16:00:46.4036510Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-01-17T16:00:46.4048345Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-01-17T16:00:46.4063169Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-01-17T16:00:46.4075474Z ##[debug]   at Microsoft.Azure.Management.DataFactory.DatasetsOperationsExtensions.<ListByFactoryNextAsync>d__9.MoveNext()
2022-01-17T16:00:46.4087468Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2022-01-17T16:00:46.4099272Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-01-17T16:00:46.4158290Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-01-17T16:00:46.4211094Z ##[debug]   at Microsoft.Azure.Management.DataFactory.DatasetsOperationsExtensions.ListByFactoryNext(IDatasetsOperations operations, String nextPageLink)
2022-01-17T16:00:46.4219553Z ##[debug]   at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.ListDatasets(AdfEntityFilterOptions filterOptions)
2022-01-17T16:00:46.4221031Z ##[debug]   at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.FilterPSDatasets(AdfEntityFilterOptions filterOptions)
2022-01-17T16:00:46.4222293Z ##[debug]   at Microsoft.Azure.Commands.DataFactoryV2.GetAzureDataFactoryDatasetCommand.ExecuteCmdlet()
2022-01-17T16:00:46.4223484Z ##[debug]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2022-01-17T16:00:46.4225964Z ##[error]Can not convert Object to String.
2022-01-17T16:00:46.4229082Z ##[debug]Processed: ##vso[task.logissue type=error]Can not convert Object to String.
2022-01-17T16:00:46.4238815Z ##[debug]Processed: ##vso[task.complete result=Failed]
2022-01-17T16:00:46.4991906Z ##[section]Finishing: Publish ADF PRUSA-DW-ADF-QA from JSON files

**Comment by crp746rb** [comment]
Found my problem dataset.  It is using a parameter for a compression type.

**Comment by NowinskiK** [comment]
You can use this PowerShell script to find the culprit:
(remember to replace variables' values in the first 2 lines)

```powershell

# Variables
$rg      = 'rg-datafactory'
$adfName = 'SQLPlayerDemo'

# Retrieve all datasets via API without parsing
$token = Get-AzAccessToken -ResourceUrl 'https://management.azure.com'
$authHeader = @{
    'Content-Type'  = 'application/json'
    'Authorization' = 'Bearer ' + $token.Token
}
$adf = Get-AzDataFactoryV2 -ResourceGroupName $rg -DataFactoryName $adfName
$adf
$url = "https://management.azure.com$($adf.DataFactoryId)/datasets?api-version=2018-06-01"
$url

# Retrieve datasets one by one via Az.DataFactory module
$ErrorActionPreference = 'Stop'
$r = Invoke-RestMethod -Method Get -Uri $url -Headers $authHeader -ContentType "application/json"
$dsArray = $r.Value
foreach ($ds in $dsArray) {
    Write-Host "Reading dataset: $($ds.name) ..."
    Get-AzDataFactoryV2Dataset -ResourceGroupName $rg -DataFactoryName $adfName -Name $ds.name
}
```

**Comment by NowinskiK** [comment]
Can you share that dataset (without sensitive information) as a file with the others here?

**Comment by crp746rb** [comment]
Nothing sensitive in the dataset, see the attached file, I was able to recreate the error using the PowerShell command.

[ds_distrib_ftp_list_read.txt](https://github.com/SQLPlayer/azure.datafactory.tools/files/7884343/ds_distrib_ftp_list_read.txt)

**Comment by NowinskiK** [comment]
This error is apparently fixed now by Microsoft.
