### ISSUE TITLE
Error in replacing property using config.csv when empty element exists

### ISSUE THREAD

**Issue by card78** [SQLPlayer/azure.datafactory.tools#186]
Hi,

Below are the contents of config.csv and the dataset OB_CosmosDB_sink.json which has the property I want to replace. Below is  the log of the run. Please let me know if my config.csv is written correctly.

config.csv
--------------------------
dataset,OB_CosmosDB_sink,linkedServiceName.referenceName,"LS_OBCosmosDb"

OB_CosmosDB_sink.json
--------------------------
{
	"name": "OB_CosmosDB_sink",
	"properties": {
		"linkedServiceName": {
			"referenceName": "LS_CosmosDbUat",
			"type": "LinkedServiceReference"
		},
		"parameters": {
			"TargetName": {
				"type": "string"
			}
		},
		"folder": {
			"name": "OB"
		},
		"annotations": [],
		"type": "CosmosDbSqlApiCollection",
		"schema": {},
		"typeProperties": {
			"collectionName": {
				"value": "@dataset().TargetName",
				"type": "Expression"
			}
		}
	}
}

Log of Run
-------------------------
2022-02-23T03:12:23.2512127Z ##[debug]- Performing: update for object(path): dataset.OB_CosmosDB_sink(properties.linkedServiceName.referenceName)
2022-02-23T03:12:23.2516790Z ##[debug]Entering Function: ConvertFrom-ArraysToOrderedHashTables
2022-02-23T03:12:23.2535781Z ##[debug]Processing PSCustomObject...
2022-02-23T03:12:23.2554672Z ##[debug]Properties: name properties
2022-02-23T03:12:23.2573923Z ##[debug]Processing property 'name' of type  String
2022-02-23T03:12:23.2592011Z ##[debug]Processing property 'properties' of type  PSCustomObject
2022-02-23T03:12:23.2610918Z ##[debug]Converting PSCustomObject property using a recursive function call...
2022-02-23T03:12:23.2974288Z ##[debug]Entering Function: ConvertFrom-ArraysToOrderedHashTables
2022-02-23T03:12:23.3007326Z ##[debug]Processing PSCustomObject...
2022-02-23T03:12:23.3027246Z ##[debug]Properties: linkedServiceName parameters folder annotations type schema typeProperties
2022-02-23T03:12:23.3057810Z ##[debug]Processing property 'linkedServiceName' of type  PSCustomObject
2022-02-23T03:12:23.3077925Z ##[debug]Converting PSCustomObject property using a recursive function call...
2022-02-23T03:12:23.3097758Z ##[debug]Entering Function: ConvertFrom-ArraysToOrderedHashTables
2022-02-23T03:12:23.3116112Z ##[debug]Processing PSCustomObject...
2022-02-23T03:12:23.3135444Z ##[debug]Properties: referenceName type
2022-02-23T03:12:23.3154318Z ##[debug]Processing property 'referenceName' of type  String
2022-02-23T03:12:23.3173028Z ##[debug]Processing property 'type' of type  String
2022-02-23T03:12:23.3224273Z ##[debug]Processing property 'parameters' of type  PSCustomObject
2022-02-23T03:12:23.3246397Z ##[debug]Converting PSCustomObject property using a recursive function call...
2022-02-23T03:12:23.3265769Z ##[debug]Entering Function: ConvertFrom-ArraysToOrderedHashTables
2022-02-23T03:12:23.3284463Z ##[debug]Processing PSCustomObject...
2022-02-23T03:12:23.3303290Z ##[debug]Properties: TargetName
2022-02-23T03:12:23.3332101Z ##[debug]Processing property 'TargetName' of type  PSCustomObject
2022-02-23T03:12:23.3350680Z ##[debug]Converting PSCustomObject property using a recursive function call...
2022-02-23T03:12:23.3370680Z ##[debug]Entering Function: ConvertFrom-ArraysToOrderedHashTables
2022-02-23T03:12:23.3389035Z ##[debug]Processing PSCustomObject...
2022-02-23T03:12:23.3408312Z ##[debug]Properties: type
2022-02-23T03:12:23.3426827Z ##[debug]Processing property 'type' of type  String
2022-02-23T03:12:23.3497054Z ##[debug]Processing property 'folder' of type  PSCustomObject
2022-02-23T03:12:23.3515603Z ##[debug]Converting PSCustomObject property using a recursive function call...
2022-02-23T03:12:23.3534487Z ##[debug]Entering Function: ConvertFrom-ArraysToOrderedHashTables
2022-02-23T03:12:23.3553077Z ##[debug]Processing PSCustomObject...
2022-02-23T03:12:23.3571477Z ##[debug]Properties: name
2022-02-23T03:12:23.3590140Z ##[debug]Processing property 'name' of type  String
2022-02-23T03:12:23.3629581Z ##[debug]Processing property 'annotations' of type  Object[]
2022-02-23T03:12:23.3648777Z ##[debug]Processing property 'type' of type  String
2022-02-23T03:12:23.3677067Z ##[debug]Processing property 'schema' of type  PSCustomObject
2022-02-23T03:12:23.3695333Z ##[debug]Converting PSCustomObject property using a recursive function call...
2022-02-23T03:12:23.3715914Z ##[debug]Entering Function: ConvertFrom-ArraysToOrderedHashTables
2022-02-23T03:12:23.3734093Z ##[debug]Processing PSCustomObject...
2022-02-23T03:12:23.4901723Z ##[debug]Leaving D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.11.1070\PublishADF.ps1.
2022-02-23T03:12:23.4946107Z ##[debug]Caught exception from task script.
2022-02-23T03:12:23.4978365Z ##[debug]Error record:
2022-02-23T03:12:23.5547650Z ##[debug]ConvertFrom-ArraysToOrderedHashTables : The property 'Name' cannot be found on this object. Verify that the property exists.
2022-02-23T03:12:23.5561389Z ##[debug]At D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.11.1070\ps_modules\azure.datafactory.tools\private\ConvertFrom-ArraysToOrderedHashTables.ps1:52 char:31
2022-02-23T03:12:23.5574774Z ##[debug]+ ... Item.$prop = ConvertFrom-ArraysToOrderedHashTables -Item $Item.$prop;
2022-02-23T03:12:23.5588155Z ##[debug]+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-02-23T03:12:23.5601694Z ##[debug]    + CategoryInfo          : InvalidOperation: (:) [ConvertFrom-ArraysToOrderedHashTables], RuntimeException
2022-02-23T03:12:23.5614905Z ##[debug]    + FullyQualifiedErrorId : PropertyNotFoundStrict,ConvertFrom-ArraysToOrderedHashTables
2022-02-23T03:12:23.5627579Z ##[debug] 
2022-02-23T03:12:23.5647232Z ##[debug]Script stack trace:
2022-02-23T03:12:23.5684799Z ##[debug]at ConvertFrom-ArraysToOrderedHashTables, D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.11.1070\ps_modules\azure.datafactory.tools\private\ConvertFrom-ArraysToOrderedHashTables.ps1: line 15
2022-02-23T03:12:23.5697730Z ##[debug]at ConvertFrom-ArraysToOrderedHashTables, D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.11.1070\ps_modules\azure.datafactory.tools\private\ConvertFrom-ArraysToOrderedHashTables.ps1: line 52
2022-02-23T03:12:23.5710788Z ##[debug]at ConvertFrom-ArraysToOrderedHashTables, D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.11.1070\ps_modules\azure.datafactory.tools\private\ConvertFrom-ArraysToOrderedHashTables.ps1: line 52
2022-02-23T03:12:23.5725291Z ##[debug]at Update-PropertiesForObject, D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.11.1070\ps_modules\azure.datafactory.tools\private\Update-PropertiesFromFile.ps1: line 105
2022-02-23T03:12:23.5738460Z ##[debug]at <ScriptBlock>, D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.11.1070\ps_modules\azure.datafactory.tools\private\Update-PropertiesFromFile.ps1: line 75
2022-02-23T03:12:23.5751731Z ##[debug]at <ScriptBlock>, D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.11.1070\ps_modules\azure.datafactory.tools\private\Update-PropertiesFromFile.ps1: line 74
2022-02-23T03:12:23.5765044Z ##[debug]at Update-PropertiesFromFile, D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.11.1070\ps_modules\azure.datafactory.tools\private\Update-PropertiesFromFile.ps1: line 39
2022-02-23T03:12:23.5778049Z ##[debug]at Publish-AdfV2FromJson, D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.11.1070\ps_modules\azure.datafactory.tools\public\Publish-AdfV2FromJson.ps1: line 187
2022-02-23T03:12:23.5791192Z ##[debug]at <ScriptBlock>, D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.11.1070\PublishADF.ps1: line 128
2022-02-23T03:12:23.5804120Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-02-23T03:12:23.5817542Z ##[debug]at <ScriptBlock>, <No file>: line 22
2022-02-23T03:12:23.5830956Z ##[debug]at <ScriptBlock>, <No file>: line 18
2022-02-23T03:12:23.5844078Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-02-23T03:12:23.5864052Z ##[debug]Exception:
2022-02-23T03:12:23.5909944Z ##[debug]System.Management.Automation.RuntimeException: The property 'Name' cannot be found on this object. Verify that the property exists.
2022-02-23T03:12:23.5923096Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2022-02-23T03:12:23.5936267Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2022-02-23T03:12:23.5949429Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2022-02-23T03:12:23.5962542Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2022-02-23T03:12:23.5975650Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2022-02-23T03:12:23.5988861Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2022-02-23T03:12:23.6001943Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2022-02-23T03:12:23.6014990Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2022-02-23T03:12:23.6027969Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2022-02-23T03:12:23.6102331Z ##[error]The property 'Name' cannot be found on this object. Verify that the property exists.
2022-02-23T03:12:23.6104259Z ##[debug]Processed: ##vso[task.logissue type=error]The property 'Name' cannot be found on this object. Verify that the property exists.
2022-02-23T03:12:23.6125485Z ##[debug]Processed: ##vso[task.complete result=Failed]
2022-02-23T03:12:23.6751766Z ##[section]Finishing: PublishADFTask

**Comment by NowinskiK** [comment]
I found that the problem is due to empty `schema` element:
![image](https://user-images.githubusercontent.com/25029325/155399879-bf596435-084b-4c48-af60-9a540f732bbf.png)

Try (if you can) put something in there as a workaround.
