### ISSUE TITLE
"Unable to deserialize the response." issue with excluded objects

### ISSUE THREAD

**Issue by BeneHa** [SQLPlayer/azure.datafactory.tools#85]
Hi Kamil,
I am using you tool for deploying different ADFs and it works great, thank you for providing it!
However, I have one issue, which occures when checking the integration runtimes according to the logs, but the error message is related to a linked service: `Current JsonReader item is not an object: String. Path 'typeProperties.password',`

I have two integration runtimes (plus the default Autoresolve) which were manually linked in both ADFs, so I am excluding the from deployment using `-integrationRuntime.*`. I have other objects I want to delete if they are no longer in the source. So when I set "Delete objects not in source" to True and "Do Not delete exluced objects" also True, I get the following error. When I set "Delete objects not in source" to False, I get no error.

The only linked service that has a type property password is this one:

```
{
    "name": "REST_AUTHBASIC_GEN",
    "type": "Microsoft.DataFactory/factories/linkedservices",
    "properties": {
        "parameters": {
            "baseUrl": {
                "type": "string",
                "defaultValue": "*********"
            },
            "authSecret": {
                "type": "string",
                "defaultValue": "none"
            }
        },
        "annotations": [],
        "type": "RestService",
        "typeProperties": {
            "url": "@{linkedService().baseUrl}",
            "enableServerCertificateValidation": true,
            "authenticationType": "Basic",
            "userName": "*********",
            "password": "@{linkedService().authSecret}"
        }
    }
}
```

Error log:

```
2021-01-29T15:55:57.6234380Z STEP: Deleting objects not in source ...

2021-01-29T15:55:58.1927426Z Azure Data Factory (instance) loaded.

2021-01-29T15:55:59.2367959Z DataSets: 19 object(s) loaded.

2021-01-29T15:55:59.9618097Z IntegrationRuntimes: 2 object(s) loaded.

2021-01-29T15:56:00.3381105Z ##[debug]Leaving D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.2.1373\PublishADF.ps1.

2021-01-29T15:56:00.3537221Z ##[debug]Caught exception from task script.

2021-01-29T15:56:00.3587508Z ##[debug]Error record:

2021-01-29T15:56:00.4528390Z ##[debug]Get-AzDataFactoryV2LinkedService : Unable to deserialize the response.

2021-01-29T15:56:00.4554304Z ##[debug]At D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.2.1373\ps_modules\azure.datafactory.tools\public\Get-AdfFromService.ps1:44 char:27

2021-01-29T15:56:00.4583602Z ##[debug]+ ... dServices = Get-AzDataFactoryV2LinkedService -ResourceGroupName "$Res ...

2021-01-29T15:56:00.4635190Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2021-01-29T15:56:00.4659659Z ##[debug]    + CategoryInfo          : CloseError: (:) [Get-AzDataFactoryV2LinkedService], SerializationException

2021-01-29T15:56:00.4705206Z ##[debug]    + FullyQualifiedErrorId : Microsoft.Azure.Commands.DataFactoryV2.GetAzureDataFactoryLinkedServiceCommand

2021-01-29T15:56:00.4772668Z ##[debug] 

2021-01-29T15:56:00.4843135Z ##[debug]Script stack trace:

2021-01-29T15:56:00.4928086Z ##[debug]at Get-AdfFromService, D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.2.1373\ps_modules\azure.datafactory.tools\public\Get-AdfFromService.ps1: line 44

2021-01-29T15:56:00.4963745Z ##[debug]at Publish-AdfV2FromJson, D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.2.1373\ps_modules\azure.datafactory.tools\public\Publish-AdfV2FromJson.ps1: line 195

2021-01-29T15:56:00.4996054Z ##[debug]at <ScriptBlock>, D:\a\_tasks\PublishADFTask_1af843b5-35a0-411f-9a18-9eb7a59fb8b8\1.2.1373\PublishADF.ps1: line 128

2021-01-29T15:56:00.5025331Z ##[debug]at <ScriptBlock>, <No file>: line 1

2021-01-29T15:56:00.5057587Z ##[debug]at <ScriptBlock>, <No file>: line 22

2021-01-29T15:56:00.5097210Z ##[debug]at <ScriptBlock>, <No file>: line 18

2021-01-29T15:56:00.5126818Z ##[debug]at <ScriptBlock>, <No file>: line 1

2021-01-29T15:56:00.5253196Z ##[debug]Exception:

2021-01-29T15:56:00.5393824Z ##[debug]Microsoft.Rest.SerializationException: Unable to deserialize the response. ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path 'typeProperties.password', line 1, position 6693.

2021-01-29T15:56:00.5427802Z ##[debug]   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)

2021-01-29T15:56:00.5478659Z ##[debug]   at Microsoft.Rest.Serialization.PolymorphicDeserializeJsonConverter``1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)

2021-01-29T15:56:00.5522424Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)

2021-01-29T15:56:00.5551283Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

2021-01-29T15:56:00.5606904Z ##[debug]   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)

2021-01-29T15:56:00.5619407Z ##[debug]   at Microsoft.Rest.Serialization.PolymorphicDeserializeJsonConverter``1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)

2021-01-29T15:56:00.5648837Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)

2021-01-29T15:56:00.5825410Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)

2021-01-29T15:56:00.5882015Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

2021-01-29T15:56:00.5885088Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

2021-01-29T15:56:00.5909238Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)

2021-01-29T15:56:00.5948785Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)

2021-01-29T15:56:00.6046582Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)

2021-01-29T15:56:00.6079911Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

2021-01-29T15:56:00.6124025Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

2021-01-29T15:56:00.6177272Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

2021-01-29T15:56:00.6195295Z ##[debug]   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)

2021-01-29T15:56:00.6218901Z ##[debug]   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)

2021-01-29T15:56:00.6279243Z ##[debug]   at Microsoft.Azure.Management.DataFactory.LinkedServicesOperations.<ListByFactoryWithHttpMessagesAsync>d__5.MoveNext()

2021-01-29T15:56:00.6335841Z ##[debug]   --- End of inner exception stack trace ---

2021-01-29T15:56:00.6392649Z ##[debug]   at Microsoft.Azure.Management.DataFactory.LinkedServicesOperations.<ListByFactoryWithHttpMessagesAsync>d__5.MoveNext()

2021-01-29T15:56:00.6428565Z ##[debug]--- End of stack trace from previous location where exception was thrown ---

2021-01-29T15:56:00.6459190Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

2021-01-29T15:56:00.6494923Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

2021-01-29T15:56:00.6601121Z ##[debug]   at Microsoft.Azure.Management.DataFactory.LinkedServicesOperationsExtensions.<ListByFactoryAsync>d__1.MoveNext()

2021-01-29T15:56:00.6663241Z ##[debug]--- End of stack trace from previous location where exception was thrown ---

2021-01-29T15:56:00.6720874Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

2021-01-29T15:56:00.6751167Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

2021-01-29T15:56:00.6814398Z ##[debug]   at Microsoft.Azure.Management.DataFactory.LinkedServicesOperationsExtensions.ListByFactory(ILinkedServicesOperations operations, String resourceGroupName, String factoryName)

2021-01-29T15:56:00.6850425Z ##[debug]   at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.ListLinkedServices(AdfEntityFilterOptions filterOptions)

2021-01-29T15:56:00.6884864Z ##[debug]   at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.FilterPSLinkedServices(AdfEntityFilterOptions filterOptions)

2021-01-29T15:56:00.6915056Z ##[debug]   at Microsoft.Azure.Commands.DataFactoryV2.GetAzureDataFactoryLinkedServiceCommand.ExecuteCmdlet()

2021-01-29T15:56:00.6967227Z ##[debug]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()

2021-01-29T15:56:00.7582941Z ##[error]Unable to deserialize the response.

2021-01-29T15:56:00.7589652Z ##[debug]Processed: ##vso[task.logissue type=error]Unable to deserialize the response.

2021-01-29T15:56:00.7611489Z ##[debug]Processed: ##vso[task.complete result=Failed]
```

It would be great if you could help me out with this, thanks for your efforts!
Benedikt

**Comment by NowinskiK** [comment]
I spoke to @shawnxzq from the ADF team and here is more clarification on this issue:

> Using AKV credential and parameterize the AKV credential name is the recommended way to parameterize credentials in ADF, the guideline is not to parameterize the credential directly in ADF from security perspective. However, the UX supports it due to some historic reasons and we need to keep it there for compatibility reasons,  the PS/SDK never supports it. So, I strongly suggest you using AKV if you really need credential parameterization. From our side, we will check whether we can add reminders in document or UX first.
